kind: Deployment
apiVersion: apps/v1
metadata:
   name: webapp-deployment
spec:
   replicas: 3
   selector:     
      matchLabels:
         app: webapp-deployment
   template:
      metadata:
         labels:
            app: webapp-deployment
      spec:
         containers:
            - name: webapp-deployment
              image: rajkumarchinnasamy/newapp:latest
              imagePullPolicy: Always
              ports:
               - containerPort: 8080
---
kind: Service                             
apiVersion: v1
metadata:
  name: webapp-deployment
  labels:
    app: webapp-deployment
spec:
  ports:
    - port: 8080                               
      targetPort: 8080
      nodePort: 32141
  selector:
    app: webapp-deployment                    
  type: LoadBalancer                   
